# Configuración General de la Aplicación
spring.application.name=contactos-api
server.port=8080

# Perfil Activo por Defecto
spring.profiles.active=dev

# Configuración de OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
